<template>
  <div class="xj-page"><span class="xj-kicker">MY FIELD NOTES</span><h1 class="xj-title">我的行鉴</h1>
    <div v-if="profile" class="profile-metrics"><div class="xj-panel"><span>当前积分</span><strong>{{ profile.account.balance }}</strong></div><div class="xj-panel"><span>累计获得</span><strong>{{ profile.account.totalEarned }}</strong></div><div class="xj-panel"><span>累计打卡</span><strong>{{ profile.checkins.length }}</strong></div></div>
    <div class="xj-toolbar"><NuxtLink class="xj-button xj-button--ghost" to="/orders">报名与兑换记录</NuxtLink><NuxtLink class="xj-button xj-button--ghost" to="/friends">好友与团队</NuxtLink></div>
    <div v-if="profile" class="profile-grid"><section class="xj-panel"><h2>最近足迹</h2><div v-for="item in profile.checkins" :key="item.id" class="timeline"><span>{{ item.cityName }}</span><strong>{{ item.pointName }}</strong><em>+{{ item.pointsAwarded }} PTS</em></div><div v-if="!profile.checkins.length" class="xj-empty">还没有打卡记录</div></section><section class="xj-panel"><h2>积分流水</h2><div v-for="item in profile.ledger" :key="item.id" class="timeline"><span>{{ item.businessType }}</span><strong>{{ item.description }}</strong><em :class="{minus:item.changeAmount<0}">{{ item.changeAmount>0?'+':'' }}{{ item.changeAmount }}</em></div><div v-if="!profile.ledger.length" class="xj-empty">还没有积分流水</div></section><section class="xj-panel"><h2>已获得徽章</h2><div class="badge-grid"><div v-for="badge in profile.badges" :key="badge.id" class="badge"><span>◎</span><div><strong>{{ badge.name }}</strong><p>{{ badge.description }}</p></div></div></div><div v-if="!profile.badges.length" class="xj-empty">完成首次打卡即可获得徽章</div></section><section class="xj-panel"><h2>完成路线</h2><div v-for="item in profile.completedRoutes" :key="item.id" class="timeline"><span>ROUTE</span><strong>{{ item.name }}</strong><em>+{{ item.pointsAwarded }}</em></div><div v-if="!profile.completedRoutes.length" class="xj-empty">还没有完成路线</div></section></div>
  </div>
</template>
<script setup lang="ts">definePageMeta({layout:'xingjian',middleware:'auth'});const{data}=await useFetch<any>('/api/me/xingjian');const profile=computed(()=>data.value?.data)</script>
<style scoped lang="scss">.profile-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin:40px 0}.profile-metrics span{color:rgba(255,255,255,.4)}.profile-metrics strong{display:block;margin-top:16px;font-size:44px;color:#f4ff58}.profile-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.profile-grid h2{margin-bottom:20px}.timeline{display:grid;grid-template-columns:80px 1fr auto;gap:12px;padding:16px 0;border-bottom:1px solid rgba(255,255,255,.08)}.timeline span{color:rgba(255,255,255,.35)}.timeline em{color:#f4ff58;font-style:normal}.timeline em.minus{color:#ff7676}.badge-grid{display:grid;gap:12px}.badge{display:flex;gap:15px;padding:14px;border:1px solid rgba(255,255,255,.08);border-radius:10px}.badge>span{font-size:30px;color:#f4ff58}.badge p{margin-top:5px;color:rgba(255,255,255,.38)}</style>
